// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiKsrbjnjmDP7U30J4OMeW-127LUmRNnk',
    appId: '1:596802340673:web:035b32f0ca8aa4b5e683c0',
    messagingSenderId: '596802340673',
    projectId: 'todo-app-a6832',
    authDomain: 'todo-app-a6832.firebaseapp.com',
    storageBucket: 'todo-app-a6832.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7xV4mjYbjMNrv_UVMdC_fAy3y5Wq3BtU',
    appId: '1:596802340673:android:42dbe8c9f3a4aebbe683c0',
    messagingSenderId: '596802340673',
    projectId: 'todo-app-a6832',
    storageBucket: 'todo-app-a6832.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAamfTlgNIF-aXO7ZAyz3Zhy1AFnodk7U4',
    appId: '1:596802340673:ios:fc3c760ba08f4bcae683c0',
    messagingSenderId: '596802340673',
    projectId: 'todo-app-a6832',
    storageBucket: 'todo-app-a6832.appspot.com',
    iosBundleId: 'com.google.todoApp.dev',
  );

}